inherit: 
    - models/standard.yaml
    - wandb.yaml

model:
    n_dims: 5
    n_positions: 101

training:
    task: linear_classification
    data: mix_gaussian
    task_kwargs: {}
    batch_size: 64
    learning_rate: 0.0001
    save_every_steps: 1000
    keep_every_steps: 50000
    train_steps: 50001
    curriculum:
        dims:
            start: 5
            end: 5
            inc: 1
            interval: 50000
        points:
            start: 11
            end: 41
            inc: 2
            interval: 2000

out_dir: ../models/linear_classification

wandb:
    name: "linear_classification"
